#!/usr/bin/env bash
 clear
  echo && echo -e "\033[0m # Fonte padrão"
   echo && echo " Código:~ \033[0m Fonte padrão"
  echo && echo -e "\033[1m # Fonte padrão com efeito bold"
   echo && echo " Código:~ \033[1m Fonte padrão com efeito bold"
  echo && echo -e "\033[3m # Fonte padrão em itálico \033[0m"
   echo && echo " Código:~ \033[3m Fonte padrão em itálico"
  echo && echo -e "\033[4m # Fonte padrão sublinhada\033[0m"
   echo && echo " Código:~ \033[4mFonte padrão sublinhada"
  echo && echo -e "\033[31m # Fonte de cor vermelha"
   echo && echo " Código:~ \033[31m Fonte de cor vermelha"
  echo && echo -e "\033[32m # Fonte de cor verde claro"
   echo && echo " Código:~ \033[32m Fonte de cor verde"
  echo && echo -e "\033[33m Fonte de cor laranja"
   echo && echo " Código:~ \033[33m Fonte de cor laranja"
  echo && echo -e "\033[34m Fonte de cor azul"
   echo && echo " Código:~ \033[34m Fonte de cor azul"
  echo && echo -e "\033[35m Fonte de cor roxa"
   echo && echo " Código:~ \033[35m Fonte de cor roxa"
  echo && echo -e "\033[36m Fonte de cor verde água"
   echo && echo " Código:~ \033[36m Fonte de cor verde água"
 echo && exit
